### ISSUE TITLE
[REQUEST] Improved style display

### ISSUE THREAD

**Issue by aparajita** [dheid/fontchooser#109]
Thank you for this great font chooser!

**Is your feature request related to a problem? Please describe.**
The display of style names is currently not a human-readable form of the original.

**Describe the solution you'd like**
I implemented a PS name parser/transformer to display human-readable style names.

**Additional context**
You can find the repo here: https://github.com/aparajita/fontchooser. The style list and model use the [`StyleEntry`](https://github.com/aparajita/fontchooser/blob/main/src/main/java/org/example/fontchooser/panes/StyleEntry.java) class, which does the work of parsing/transforming the font's PS name.

Hope you find this useful! 🙏

**Comment by dheid** [comment]
Sounds great! Thank you! Do you want to help and create a pull request for that, please?

**Comment by aparajita** [comment]
I didn't fork because I made a bunch of changes, so a PR would take time which I unfortunately don't have right now.
