### ISSUE TITLE
Can I select only monospace fonts?

### ISSUE THREAD

**Issue by dzmipt** [dheid/fontchooser#41]
**Is your feature request related to a problem? Please describe.**
I want to use the font chooser for an editor and be able to select only monospace fonts. 

**Describe the solution you'd like**
Probably the best option would be a checkbox in the FontChooser panel to filter only monospace fonts. 

I didn't find how to determine in Java in a Font is monospace or not. I would take some characters like space, x, i, W and check if they render to the same width.

**Describe alternatives you've considered**
Another possible option would be to allow users of the library to initialise the list of fonts to select from.

**Comment by dheid** [comment]
Thanks for the request. A checkbox would be an extra action for the user and as far as I understand you want to enforce monospace fonts, right? How about a boolean option before creating the font chooser to only show monospaced fonts?

**Comment by dzmipt** [comment]
In my case, I think that users would prefer to have monospace fonts. However I would leave this decision to user. If he/she wants to choose from monospace fonts, they click the checkbox

**Comment by dheid** [comment]
@dzmipt I implemented and released this recently. Very late, sorry. There is a checkbox to filter the monospaced fonts now.
